apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.breviai.brevisettings'
version = '1.0.0'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    namespace "com.breviai.brevisettings"
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.kotlinVersion}"
    implementation 'com.sun.mail:android-mail:1.6.7'
    implementation 'com.sun.mail:android-activation:1.6.7'
    implementation 'org.jsoup:jsoup:1.15.3'
}
